on:
  push:
    branches:
      - main  # ou outra branch que deseje monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command
        run: |
          echo "Hello, World!"
